### PR TITLE
added contributing file

### PR DESCRIPTION
**Pull request by Sloth-Panda**
issue: #51 

@srimani-programmer 

please add "gssoc21" and "level1/level2/level3"  tag to both issue and pr

### CODE REVIEW

**Comment by srimani-programmer** [comment]
Please ping me the tags related details properly. So I can make changes to the repo

**Comment by Sloth-Panda** [comment]
@srimani-programmer you can add 
Either gssoc21 or GSSOC21 one among them

And for the points  part add levels like 

1. level0
2. level1
3.  level2
4.  level3
They are 5,10,15,25 points repectively

So he have to add one of the gssoc tag and one level tag intotal 2 to both issue and prs

**Comment by Sloth-Panda** [comment]
@srimani-programmer bro can you please check this pr, and please add those tags too that you have added to the issue to this pr. thank you!

**Comment by srimani-programmer** [comment]
@Sloth-Panda Are you working on this PR or not? please reply to this thread.

**Pull request closed without merging**
