### PR TITLE
Develop a website for our application 

### PR DESCRIPTION
**Pull request by anushavc**
This is my solution for the issue #16 .  Kindly let me know if it needs any changes

### CODE REVIEW

**Comment by srimani-programmer** [comment]
@anushavc Could you please make a demo video and upload it into the drive folder and share the link please then it would be easy for the review. The video doesn't require any voice but adding voice gives more clarity. The video should contain a developed website.

**Comment by anushavc** [comment]
sure

**Comment by anushavc** [comment]
Should i deploy the website as well? as i have only made changes in the html and css files

**Comment by srimani-programmer** [comment]
@anushavc  Just run locally on your system and record the video upload it.

**Comment by anushavc** [comment]
https://drive.google.com/file/d/129hO2D5WJJ-zaJyxckmCKvxuCW9CVpwZ/view?usp=sharing

**Comment by srimani-programmer** [comment]
@anushavc Application looks good. But the Form is not so good. Could you please remake the entire form section? Once made the changes, please make the PR. Surely you will get extra bonus points.

**Comment by anushavc** [comment]
Made changes to the form section. let me know if it still needs any more changes.

https://drive.google.com/file/d/1BONfwBOx1_Dkxkg86nRe61eb3oAnpoki/view?usp=sharing

**Comment by srimani-programmer** [comment]
@anushavc Sorry to say this could you please make form some more innovative and make PR.

**Comment by anushavc** [comment]
I made some more changes to the entire form section. Do let me know if it needs any other changes
https://drive.google.com/file/d/1QrnVDgB59U0siGJEj3FQMnTI7qa0mNdm/view?usp=sharing

**Comment by srimani-programmer** [comment]
@anushavc Excellent.! Could you please add any designed logo / some interesting item on the left hand side.

**Comment by anushavc** [comment]
image

if this is okay, i will go ahead and make PR

**Comment by anushavc** [comment]
image
 
is this okay?

**Comment by srimani-programmer** [comment]
@anushavc yeah.! For now I'm merging this issue. I will create few more issues separately for this website only. Then you can work on it.

**Pull request merged**
