### PR TITLE
404 error handle code and template

### PR DESCRIPTION
**Pull request by arpit456jain**
404 error handle code and template

Fixes : #145 

https://user-images.githubusercontent.com/55352601/120116329-4ff2aa00-c1a5-11eb-8dc2-f06b2855d46e.mp4

### CODE REVIEW

**Comment by arpit456jain** [comment]
@srimani-programmer please review this PR.
I am expecting  lvl3 for this PR

**Comment by srimanikantapalakollu** [comment]
@arpit456jain Sorry to say this Your contribution to this PR is plagiarised. This kind of behavior is pathetic in Open Source Community. I need to reverify your previous contributions as well and also You need to be responsible for what you have done. please respond to me with proper explanation.

**Comment by arpit456jain** [comment]
@srimani-programmer i had modified the code after borrow i had not just copy paste

**Comment by arpit456jain** [comment]
And what do you mean by plagiarized. There is no copyright to that code or template

**Comment by arpit456jain** [comment]
How can i produce a new code for handling that error .
There are some buil in function defined and i just used them 
What's wrong in that @srimani-programmer

**Comment by srimanikantapalakollu** [comment]
@arpit456jain please don't argue with me. Your contribution is not unique and you didn't followed the code of conduct mentioned by GSSOC'21.

**Comment by arpit456jain** [comment]
> @arpit456jain please don't argue with me. Your contribution is not unique and you didn't followed the code of conduct mentioned by GSSOC'21.

Ok no problem you can close this pr

**Pull request closed without merging**
