### PR TITLE
New Our team section

### PR DESCRIPTION
**Pull request by arpit456jain**
New Our team section
Fixes : #142 

https://user-images.githubusercontent.com/55352601/119247285-cab83580-bba5-11eb-862c-b42d3c1c3fbe.mp4

### CODE REVIEW

**Comment by arpit456jain** [comment]
@srimani-programmer kindly review this PR .  I hope you like the new our team section

**Review by srimanikantapalakollu — CHANGES_REQUESTED** [review]
@arpit456jain kindly reduce the font size a little bit for "Meet the contributors!" caption.

**Comment by arpit456jain** [comment]
> @arpit456jain kindly reduce the font size a little bit for "Meet the contributors!" caption.

@srimani-programmer i am already working on this on a new branch , will optimize the font-size of all the heading in desktop view and mobile view.
Don't worry

**Comment by arpit456jain** [comment]
@srimani-programmer please merge this PR . dont't worry about font-size it will be fixed on by another branch with other headings  , they are very big in small screen . i am already working on it in issue  #141 .
So need of making this change in this branch . it will cause merge conflicts

**Comment by arpit456jain** [comment]
@srimani-programmer kindly merge this so that i can make Pr for other issue #141  otherwise merge conflicts will occur

**Comment by arpit456jain** [comment]
aaa

@srimani-programmer

**Comment by arpit456jain** [comment]
@srimani-programmer kindly merge this PR

**Pull request merged**
