### PR TITLE
docs: Added Issue templates

### LINKED ISSUE #158: docs: Add Issue Templates
### Chnages 
- Adding Issue templates
- Template path **`.github/ISSUE_TEMPLATE`**

###Template Types
Screenshot from 2022-03-01 21-03-49

### Template Preview (while creating an issue - bug.)
Screenshot from 2022-03-01 18-03-48

####  Due to that we are also missing out on some checks on the community standards checklist

Screenshot from 2022-03-01 21-22-52

- Contribution towards GSsoc`22, Thank you

### PR DESCRIPTION
**Pull request by Pradumnasaraf**
### Fix

closes #158 

### Changes 

- Added 3 issue templates.

### CODE REVIEW

**Comment by Pradumnasaraf** [comment]
Hey @srimani-programmer, please review this PR, thank you

**Comment by Pradumnasaraf** [comment]
Hey @srimani-programmer, please review this PR, thank you

**Comment by freny24** [comment]
@Pradumnasaraf Good work! Your PR is merged

**Comment by Pradumnasaraf** [comment]
> @Pradumnasaraf Good work! Your PR is merged

Thank you, one more is open please have a look https://github.com/srimani-programmer/Breast-Cancer-Predictor/pull/207

**Pull request merged**
