### PR TITLE
Create PULL_REQUEST_TEMPLATE.md

### LINKED ISSUE #82: Pull request template missing
PR template is an important feature of any repo. When we create a PR (Pull Request),  PR template ask some conditions which are necessary to fullfill before submitting a PR. This is missing in this project.

### PR DESCRIPTION
**Pull request by Subhangini**
Fixes #82

### CODE REVIEW

**Review by srimani-programmer — CHANGES_REQUESTED** [review]
@Subhangini please make your PR to the new_pipeline branch, not to the master branch.

**Comment by Subhangini** [comment]
ok

**Comment by Subhangini** [comment]
done

**Comment by Subhangini** [comment]
Please review it

**Review by srimani-programmer — APPROVED** [review]

**Pull request merged**
