### PR TITLE
Created the Logo for this project.

### PR DESCRIPTION
**Pull request by amandp13**
- [x]  Unique Logo
- [x]  Simple One, non-offensive.
- [x]  Following the Guidelines.

### CODE REVIEW

**Review by srimani-programmer — CHANGES_REQUESTED** [review]
The logo is unique and good. You really did a great job. Try to make some modification that brings good attraction to the logo. please proceed to make the logo more attractive and meaningful. I hope you got my point.

**Comment by amandp13** [comment]
@srimani-programmer Should I change the color of the logo to make it more attractive?
Also, should I add more text to the Logo?

I think it looks decent if the Logo stays simple.

**Comment by srimani-programmer** [comment]
@amandp13 yeah proceed with it.

**Comment by amandp13** [comment]
@srimani-programmer Done. Please Approve

**Comment by amandp13** [comment]
@srimani-programmer Done. 
Please Merge this PR Tomorrow.

**Comment by srimani-programmer** [comment]
@amandp13 colour is okay but please remove the last caption. Breast cancer predictor is enough. I guess.

**Comment by amandp13** [comment]
@srimani-programmer All changes are done. Do merge It.

**Comment by srimani-programmer** [comment]
@amandp13 I am seeing your Old Commits only please cross verify and upload the latest files to the repo.

**Comment by amandp13** [comment]
@srimani-programmer Do check now.

**Pull request merged**
