### PR TITLE
Compared Transform learning methods.

### PR DESCRIPTION
**Pull request by Keyurchaniyara**
I compared 3 transform learning methods using an image dataset with good accuracy.
issue no. #199

### CODE REVIEW

**Comment by Keyurchaniyara** [comment]
I completed my task and compared transform learning techniques' accuracy.

**Comment by freny24** [comment]
@Keyurchaniyara Hey! IPYNB files are not easy to integrate into flask. Please convert this into python script and submit

**Comment by srimanikantapalakollu** [comment]
@Keyurchaniyara Please make sure to raise PR to the New_Pipeline branch, not for the master branch.

**Comment by Keyurchaniyara** [comment]
changes are done via another pull request.

**Pull request closed without merging**
