### PR TITLE
[Gssoc'21] Added the back to top button and favicon

### PR DESCRIPTION
**Pull request by arpit456jain**
I had added the back to top button and a favicon because it is giving errors in console .

console should be clear.

This is the how back to top button looking and working 

https://user-images.githubusercontent.com/55352601/113410368-e470a400-93d0-11eb-8c5e-2e03ea4f6005.mp4

After making this video I had added the favicon 
Untitled

This PR will close issue #103

### CODE REVIEW

**Comment by arpit456jain** [comment]
@srimani-programmer kindly add labels of gssoc'21 and level before merging

**Comment by arpit456jain** [comment]
@srimani-programmer kindly review my PR and add labels before merging

**Comment by arpit456jain** [comment]
@srimani-programmer kindly review my PR and add labels to it

**Review by srimanikantapalakollu — CHANGES_REQUESTED** [review]
@arpit456jain please add the favicon related to the project if possible. If you have design skills please design it. or else remove the favicon and update the PR. I'll look into it.

**Comment by arpit456jain** [comment]
> @arpit456jain please add the favicon related to the project if possible. If you have design skills please design it. or else remove the favicon and update the PR. I'll look into it.

@srimani-programmer  ok i am removing it.

**Comment by arpit456jain** [comment]
> @arpit456jain please add the favicon related to the project if possible. If you have design skills please design it. or else remove the favicon and update the PR. I'll look into it.

@srimani-programmer  ok i am removing it.

**Comment by arpit456jain** [comment]
@srimani-programmer requested changes done 👍

**Review by srimanikantapalakollu — CHANGES_REQUESTED** [review]
@arpit456jain You made your PR to the master branch. please make your contribution to the new_pieline branch.

**Comment by arpit456jain** [comment]
> @arpit456jain You made your PR to the master branch. please make your contribution to the new_pieline branch.

I think i am on arpitbranch 😅

**Comment by arpit456jain** [comment]
IMG_20210417_112330

**Comment by arpit456jain** [comment]
> @arpit456jain You made your PR to the master branch. please make your contribution to the new_pieline branch.

Ok

**Comment by arpit456jain** [comment]
> @arpit456jain You made your PR to the master branch. please make your contribution to the new_pieline branch.

@srimani-programmer kindly merge it into master branch for now after adding suitable labels to it otherwise my work will be waste 
and I am creating a fresh PR after adding back to top button in your project of New_PipeLine .
because its a whole new and different  project I have to do the work again in it I can't simple merge it 

@srimani-programmer Hope You understand

**Comment by arpit456jain** [comment]
@srimani-programmer  thanks creating the issue right now

**Comment by WangeshiMaya** [comment]
am trying to clone repository but it keeps telling me (err 8)

**Pull request merged**
